# Generated by Django 3.2.4 on 2021-06-19 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NaN', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Casablanca', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lg.cities')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('boughts', models.IntegerField(blank=True, default=0)),
                ('avatar', models.ImageField(default='article/default.jpeg', upload_to='article/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lg.articlecategories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lg.userprofile')),
            ],
        ),
    ]
